name: Update Taro contributor database
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 21 * * *'

env:
  CI: true
  NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
jobs:
  Update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with :
          ref : ${{ github.head_ref }}

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.3
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Fetch notion database
        run: |
          pnpm run notion

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(date): update contributor member-list"
